site_title = "MyArxiv"
limit_days = 10
cache_url = "https://w1994wl202.github.io/wlArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.AI"
title = "tool"

[[sources]]
limit = 150
category = "cs.AI"
title = "Reason"

[[sources]]
limit = 150
category = "cs.AI"
title = "Reinforcement Learning"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
